"""
llm_agent
~~~~~~~~~
Stage 3 of the AI refactoring pipeline.

Reads prompts generated by Stage 2, sends them to an LLM via the google-genai
API, extracts the returned code blocks, and applies the refactored code
back to the source files.
"""

from llm_agent.run_agent import run

__all__ = ["run"]
__version__ = "1.0.0"
